# -*- coding: utf-8 -*-
"""BajajFinserv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uwoCtMnBvxlVCRczJ4khRvlYqiOM44fr
"""





from flask import Flask, jsonify, request
from flask_ngrok import run_with_ngrok
import json
app=Flask(__name__)

@app.route('/',methods=["GET"])
def main():
  a={
      "is_success": True,
      "user_id": "john_doe_17091999", 
      "odd": [1,3,5,7,9],
      "even": [0,2,4,6,8]
  }
  return jsonify(a)
@app.route('/bfhl', methods=["GET","POST"])
def new():
  data=request.get_json()
  if data==None:
    return("NO data found")
  number=data["numbers"]
  
  odd=[]
  even=[]
  final={}
  userid="vardangarg_29052000"
  status = True
  for i in number:
      if i.isnumeric():
          if int(i)%2==0:
              even.append(int(i))
          else:
              odd.append(int(i))
      else:
          status=False
          break
  if status:
      final["is_success"]=status
      final["user_id"]= userid
      final["odd"] = odd
      final["even"] = even
  else:
      final["is_success"]=status
      final["user_id"]= userid

  return jsonify(final)

if __name__=="__main__":
    app.run()
